name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up the deployment directory
      - name: Prepare Deployment Files
        run: |
          mkdir -p deploy
          cp index.html cloudflare.js deploy/

      # Step 3: Deploy to GitHub Pages using peaceiris/actions-gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages          # Branch to deploy to
          publish_dir: ./deploy             # Directory with files to deploy
          keep_files: false                  # Overwrite existing files
