name: GitHub Pages Deployment

on:
  push:
    branches:
      - main  # Change this if you use a different default branch
  workflow_dispatch:

permissions:
  contents: read  # Allows the workflow to clone the repository
  pages: write    # Allows the workflow to write to the GitHub Pages site
  id-token: write # Allows the workflow to authenticate with GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      # If you need to build your site (e.g., using a static site generator), add build steps here
      # Since you're deploying static files, you can skip directly to deploying

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'  # Adjust this if your files are in a subdirectory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
